# Simple workflow for deploying static content to GitHub Pages
name: Publish Docs

on:
  # Runs when released
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
env:
  NODE_VERSION: 22.x
jobs:
  # Single deploy job since we're just deploying
  deploy_to_pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check cache
        id: cache
        uses: actions/cache@v4
        with:
          path: packages/sdk/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-0
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@chili-publish"
      - name: install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build documentation to md
        run: yarn build-docs-md
      - name: build documentation to html
        run: yarn build-docs-html
      - name: Verify docs directory
        run: |
          ls -la packages/sdk/docs/html
          echo "Verifying documentation files exist..."
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/sdk/docs/html"
          name: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: docs
