name: Monorepo-Test
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PACKAGE_SECRET }}
            - name: bump version
              uses: phips28/gh-action-bump-version@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_SECRET }}
              with:
                  minor-wording: 'Feature,FEATURE'
                  major-wording: 'Breaking,BREAKING'
                  patch-wording: 'Fix,FIX' 
                  skip-commit:  'true'
                  skip-tag: 'true'

            # execute local js script
            - name: execute local js script
              run: node ./.github/scripts/replicate-version.js
            # execute commit script
            - name: execute commit script
              run: node ./.github/scripts/commit.js
